version: '3.8'
services:
  paciente:
    build: ./paciente
    ports:
      - "5001:5001"

  consulta:
    build: ./consulta
    ports:
      - "5002:5002"
    depends_on:
      - paciente

  prontuario:
    build: ./prontuario
    ports:
      - "5003:5003"
    depends_on:
      - consulta

  faturamento:
    build: ./faturamento
    ports:
      - "5004:5004"
    depends_on:
      - prontuario

